movierecommender/urls.py
from django.urls import path
from . import views

app_name ="movierecommender"

urlpatterns = [
    # route is a string contains a URL pattern
    path(route='', view=views.home, name= 'home'),
    path(route='filtered/', view=views.filtered, name='filtered'),
    path(route='recommendations/', view = views.movie_recommendation_view, name='recommendations'),
]

recommender/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movierecommender.urls'))
]

#path('movierecommender/', include('movierecommender.urls'))

movierecommender/models.py
from django.db import models


# Create your models here.
# HINT: Create a Movie model here
# It will be mapped to a database table with columns
class Movie(models.Model):
    """
    Django Movie Model
    """
    # IMDB id
    imdb_id = models.CharField(max_length=48, null=False)
    # Movie genres
    genres = models.CharField(max_length=200, null=True)
    # Original language
    original_language = models.CharField(max_length=20, null=True)
    # Original movie title
    original_title = models.CharField(max_length=500, null=False)
    # Movie release date
    release_date = models.IntegerField(default=1970)
    # Movie overview
    overview = models.TextField(max_length=2000, null=True)
    # Average voting for the movie
    vote_average = models.FloatField(default=0)
    # Total votes for ths movie
    vote_count = models.IntegerField(default=0)
    # The movie's poster path
    poster_path = models.CharField(max_length=64, null=True)
    # If you have watched this movie
    watched = models.BooleanField(default=False, null=True)
    # If this movie will be recommended
    recommended = models.BooleanField(default=False, null=True)

movierecommender/forms.py
from django import forms
from .models import Movie

class formulario(forms.ModelForm):

    class Meta:
        model = Movie
        fields =['genres']

movierecommender/views.py
from . import views
from .models import Movie
from django.shortcuts import render
from .forms import formulario

# HINT: Create a view to provide movie recommendations list for the HTML template
def home(request):
    context=generate_movies_forhome()

    return render(request, 'movierecommender/home.html', context)

def generate_movies_forhome():
    context={}
    movies = Movie.objects.all()[:30]
    context['movie_list'] = movies
    return context


##### FILTERING MOVIES:

def filtered(request):
    if request.method == "GET":

        context=generate_movies_filtered()
        return render(request, 'movierecommender/filtered.html', context)


def generate_movies_filtered():
    context={}

    movies = Movie.objects.filter(
        genres='romance'
        ).order_by('-vote_count')[:30]
    context['movie_list'] = movies
    return context

############################### BACKEND ################################
# Funcion 1. se actualiza con el contexto de funcion 2
def movie_recommendation_view(request):
    if request.method == "GET":
        #the context/ data to be presented in the html template
        context= generate_movies_context()
        #render a html with specified template and context
        return render(request, 'movierecommender/movie_list.html', context)

# Funcion 2.
def generate_movies_context():
    context = {}
    # Show only movies in recommendation list
    # Sorted by vote_average in desc
    # Get recommended movie counts
    recommended_count = Movie.objects.filter(
        recommended=True
    ).count()
    # If there are no recommended movies
    if recommended_count == 0:
        # Just return the top voted and unwatched movies as popular ones
        movies = Movie.objects.filter(
            watched=False
        ).order_by('-vote_count')[:30]
    else:
        # Get the top voted, unwatched, and recommended movies
        movies = Movie.objects.filter(
            watched=False
        ).filter(
            recommended=True
        ).order_by('-vote_count')[:30]
    context['movie_list'] = movies
    return context

############################### BACKEND ################################

movierecommender/templates/movierecommender/filtered.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

        <meta charset="UTF-8">
        <title>HOME</title>
    </head>

    <!--Navigation bar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'movierecommender:home' %}">Movie Recommendations Web App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'movierecommender:filtered' %}"> Filtered <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movierecommender:recommendations' %}">Recomendations</a>
      </li>

    </ul>
  </div>
</nav>



  <body>


    <div class="jumbotron jumbotron-fluid text-center">
        <div class="container">
    <h1>Movie's Filtered by Romance</h1>
    <p>Binge and watch the best rated movies</p>
        </div>
    </div>

<div class="container">
<div class="card-columns">
{% for movie in movie_list %}
<div class="col-auto mb-3">
    <div class="text-center pr-3">
      <img src="https://image.tmdb.org/t/p/original/{{movie.poster_path}}" width="320" height="480" class="rounded" alt="...">
    </div>
</div>
{% endfor %}
</div>
</div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
  </html>

movierecommender/templates/movierecommender/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

        <meta charset="UTF-8">
        <title>HOME</title>
    </head>

    <!--Navigation bar
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="navbar-header">
                      <a class="navbar-brand" href="#">Movie Recommendations Web App </a>
            </div>
        </div>
    </nav>
-->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'movierecommender:home' %}">Movie Recommendations Web App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movierecommender:filtered' %}"> Filtered {{movie.genres}} </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movierecommender:recommendations' %}">Recomendations</a>
      </li>

    </ul>
  </div>
</nav>



  <body>


    <div class="jumbotron jumbotron-fluid text-center">
        <div class="container">
    <h1>Welcome to Movie's Home</h1>
    <p>Binge and watch the latest movies carefully selected for you</p>
        </div>
    </div>


<div class="container">
<div class="card-columns">
{% for movie in movie_list %}
<div class="col-auto mb-3">
    <div class="text-center pr-3">
      <img src="https://image.tmdb.org/t/p/original/{{movie.poster_path}}" width="320" height="480" class="rounded" alt="...">
    </div>
</div>
{% endfor %}
</div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
  </html>

movierecommender/templates/movierecommender/movie_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <meta charset="UTF-8">
        <title>Personal Movie Recommendations Esteph</title>
    </head>
    <!--Navigation bar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'movierecommender:home' %}">Movie Recommendations Web App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movierecommender:filtered' %}"> Filtered <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movierecommender:recommendations' %}">Recomendations</a>
      </li>

    </ul>
  </div>
</nav>

    <div class="jumbotron jumbotron-fluid text-center">
        <div class="container">
    <h1>Movie Recommendations</h1>
    <p>Binge and watch the latest movies carefully selected for you</p>
        </div>
    </div>

    <body>
    <!--Render Movie list as card columns here -->
    <div class="container">
    <div class="card-columns">
        <!--For each movie in the movie list, add a movie card-->
        {% for movie in movie_list %}
        <div class="col-auto mb-3">
            <div class="card">
                <!--Movie Poster image-->
                <img class="card-img-left"
                     src="https://image.tmdb.org/t/p/original/{{movie.poster_path}}"
                     width="320" height="480">
                <div class="card-body bg-light">
                    <!--Movie title-->
                    <h5 class="card-title">{{movie.original_title}}</h5>
                    <!--Movie overview-->
                    <p class="card-text">{{movie.overview}}</p>
                    <!--Movie genres-->
                    <p class="card-text">Genres: <b>{{movie.genres}}</b></p>
                    <!--Movie vote average-->
                    <p class="card-text">Rating: <b>{{movie.vote_average}}</b></p>
                    <!--Movie language and release date-->
                    <p class="card-text">{{movie.original_language}}, {{movie.release_date}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
    </body>

</html>